/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 .\public\models\Punk.gltf -o src/threecomponents/Punk.jsx -r public 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Punk({hovered, ...props}) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/Punk.gltf')
  const { actions } = useAnimations(animations, group)
  // console.log(actions) prints out animations that come with model

  useEffect(() => {
    const anim = hovered ? "Wave":"Idle";
    actions[anim].reset().fadeIn(0.5).play();
    return () => actions[anim].fadeOut(0.5);
  }, [hovered]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
          <group name="Punk_Body">
            <skinnedMesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials.Skin} skeleton={nodes.Cube001.skeleton} />
            <skinnedMesh name="Cube001_1" geometry={nodes.Cube001_1.geometry} material={materials.White} skeleton={nodes.Cube001_1.skeleton} />
            <skinnedMesh name="Cube001_2" geometry={nodes.Cube001_2.geometry} material={materials.Black} skeleton={nodes.Cube001_2.skeleton} />
          </group>
          <group name="Punk_Feet">
            <skinnedMesh name="Cube208" geometry={nodes.Cube208.geometry} material={materials.Skin} skeleton={nodes.Cube208.skeleton} />
            <skinnedMesh name="Cube208_1" geometry={nodes.Cube208_1.geometry} material={materials.Black} skeleton={nodes.Cube208_1.skeleton} />
          </group>
          <group name="Punk_Head">
            <skinnedMesh name="Cube026" geometry={nodes.Cube026.geometry} material={materials.Skin} skeleton={nodes.Cube026.skeleton} />
            <skinnedMesh name="Cube026_1" geometry={nodes.Cube026_1.geometry} material={materials.Eye} skeleton={nodes.Cube026_1.skeleton} />
            <skinnedMesh name="Cube026_2" geometry={nodes.Cube026_2.geometry} material={materials.Eyebrows} skeleton={nodes.Cube026_2.skeleton} />
            <skinnedMesh name="Cube026_3" geometry={nodes.Cube026_3.geometry} material={materials.Red_Dark} skeleton={nodes.Cube026_3.skeleton} />
            <skinnedMesh name="Cube026_4" geometry={nodes.Cube026_4.geometry} material={materials.Red} skeleton={nodes.Cube026_4.skeleton} />
            <skinnedMesh name="Cube026_5" geometry={nodes.Cube026_5.geometry} material={materials.Earrings} skeleton={nodes.Cube026_5.skeleton} />
          </group>
          <group name="Punk_Legs">
            <skinnedMesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials.Skin} skeleton={nodes.Cube009.skeleton} />
            <skinnedMesh name="Cube009_1" geometry={nodes.Cube009_1.geometry} material={materials.LightBlue} skeleton={nodes.Cube009_1.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Punk.gltf')
